version: "3.9"

services:
  adminer:
    image: adminer
    ports:
      - "${FORWARD_ADMINER_PORT:-8888}:8080"
    networks:
      - intranet

  # mysql:
  #   image: "mysql/mysql-server:8.0"
  #   ports:
  #     - "${FORWARD_DB_PORT:-3306}:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
  #     MYSQL_ROOT_HOST: "%"
  #     MYSQL_DATABASE: "${DB_DATABASE}"
  #     MYSQL_USER: "${DB_USERNAME}"
  #     MYSQL_PASSWORD: "${DB_PASSWORD}"
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #   volumes:
  #     - "./docker/volumes/mysql:/var/lib/mysql"
  #     - "./docker/data:/docker-entrypoint-initdb.d"
  #   networks:
  #     - intranet
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
  #     retries: 3
  #     timeout: 5s

  # postgres:
  #   image: postgres:16
  #   ports:
  #     - ${FORWARD_DB_PORT:-5432}:5432
  #   environment:
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #     POSTGRES_DB: ${DATABASE_NAME}
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #   volumes:
  #     -  "./docker/volumes/postgresql:/var/lib/postgresql/data"
  #   networks:
  #     - intranet

  # mailhog:
  #   image: "mailhog/mailhog:latest"
  #   ports:
  #     - "${FORWARD_MAILHOG_PORT:-1025}:1025"
  #     - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
  #   networks:
  #     - intranet

networks:
  intranet:
    driver: bridge
